#! /usr/bin/python
import json
import requests
import os
import random
user='username' # this will get configured by the installer
dest='/home/{0}/Pictures/wallpaper/'.format(user)
subreddit='wallpaper'
baseurl = 'http://imgur.com'
r = requests.get(baseurl + '/r/%s/top.json' % subreddit)
j = json.loads(r.text)
data = [ img for img in j['data'] if img['width'] >= 1920 and img['height'] >= 1080 and img["ext"] != ".gif" and img["nsfw"] == False ]
best = ["%s/%s%s" % (baseurl, img['hash'], img['ext']) for img in data[:7]]
rest = data[7:]
random.shuffle(rest)
randoms = ["%s/%s%s" % (baseurl, img['hash'], img['ext']) for img in rest[:7]]
urls = best + randoms
if len(urls) == 0:
    exit(1)
for the_file in os.listdir(dest):
    file_path = os.path.join(dest, the_file)
    try:
        if os.path.isfile(file_path):
            os.unlink(file_path)
    except Exception as e:
        print e
        
for url in urls:
    r=requests.get(url)
    with open(dest + url.split('/')[-1], 'wb') as f:
        f.write(r.content)
