#! /bin/bash
wallpapers=($(find /home/$USER/Pictures/wallpaper -type f))
wallpapers+=($(find /home/$USER/Pictures/saved_wallpaper -type f))
nextWallpaper=${wallpapers[$RANDOM % ${#wallpapers[@]} ]}

echo $nextWallpaper
