#! /bin/bash
wallpapers=($(find /home/$(whoami)/Pictures/wallpaper -type f))
wallpapers+=($(find /home/$(whoami)/Pictures/saved_wallpaper -type f))
nextWallpaper=${wallpapers[$RANDOM % ${#wallpapers[@]} ]}

echo $nextWallpaper
